<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-06T21:46:27Z" name="Portal Test Suite" finished-at="2021-04-06T21:48:21Z" duration-ms="113563">
    <groups>
    </groups>
    <test started-at="2021-04-06T21:46:27Z" name="Regression_Test" finished-at="2021-04-06T21:48:21Z" duration-ms="113563">
      <class name="Jasper.Automation.Tests.Tests">
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:27Z" name="setup" finished-at="2021-04-06T15:46:35Z" duration-ms="7942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Check_provisional_text_for_Privacy()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:35Z" name="Check_provisional_text_for_Privacy" finished-at="2021-04-06T15:46:36Z" duration-ms="1440" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Jasper.Automation.Tests.Tests.Check_provisional_text_for_Privacy(Tests.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_provisional_text_for_Privacy -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:36Z" name="tearDown" finished-at="2021-04-06T15:46:43Z" duration-ms="7041" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:43Z" name="setup" finished-at="2021-04-06T15:46:51Z" duration-ms="7657" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Check_provisional_text_for_Terms_and_condition()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:51Z" name="Check_provisional_text_for_Terms_and_condition" finished-at="2021-04-06T15:46:52Z" duration-ms="1347" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Jasper.Automation.Tests.Tests.Check_provisional_text_for_Terms_and_condition(Tests.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Check_provisional_text_for_Terms_and_condition -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:52Z" name="tearDown" finished-at="2021-04-06T15:46:59Z" duration-ms="7020" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:46:59Z" name="setup" finished-at="2021-04-06T15:47:07Z" duration-ms="7691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Factorial_for_limit_value_171_is_Not_infinity()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:07Z" name="Factorial_for_limit_value_171_is_Not_infinity" finished-at="2021-04-06T15:47:13Z" duration-ms="5535" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Jasper.Automation.Tests.Tests.Factorial_for_limit_value_171_is_Not_infinity(Tests.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Factorial_for_limit_value_171_is_Not_infinity -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:13Z" name="tearDown" finished-at="2021-04-06T15:47:19Z" duration-ms="6534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:19Z" name="setup" finished-at="2021-04-06T15:47:27Z" duration-ms="8179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Get_factorial_for_limit_value_170()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:27Z" name="Get_factorial_for_limit_value_170" finished-at="2021-04-06T15:47:33Z" duration-ms="5451" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Get_factorial_for_limit_value_170 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:33Z" name="tearDown" finished-at="2021-04-06T15:47:40Z" duration-ms="7000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:40Z" name="setup" finished-at="2021-04-06T15:47:47Z" duration-ms="7435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Get_factorial_for_limit_value_zero()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:47Z" name="Get_factorial_for_limit_value_zero" finished-at="2021-04-06T15:47:53Z" duration-ms="5537" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Get_factorial_for_limit_value_zero -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:47:53Z" name="tearDown" finished-at="2021-04-06T15:48:00Z" duration-ms="7273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:48:00Z" name="setup" finished-at="2021-04-06T15:48:08Z" duration-ms="7763" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Happy_path_Get_factorial_valid_num()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:48:08Z" name="Happy_path_Get_factorial_valid_num" finished-at="2021-04-06T15:48:13Z" duration-ms="5536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Happy_path_Get_factorial_valid_num -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Jasper.Automation.Tests.Tests@291caca8]" started-at="2021-04-06T15:48:13Z" name="tearDown" finished-at="2021-04-06T15:48:20Z" duration-ms="7160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Jasper.Automation.Tests.Tests -->
    </test> <!-- Regression_Test -->
  </suite> <!-- Portal Test Suite -->
</testng-results>
